### ISSUE TITLE
Missing Assets (ModuleFast.psm1) in Release

### ISSUE THREAD

**Issue by ufukozkanli-ge** [JustinGrote/ModuleFast#101]
`Invoke-WebRequest "https://github.com/JustinGrote/ModuleFast/releases/download/v0.5.1/ModuleFast.ps1" -UseBasicParsing | Invoke-Expression`

_DEBUG: Fetching ModuleFast from https://github.com/JustinGrote/ModuleFast/releases/latest/download/ModuleFast.psm1_
**Invoke-Expression: You cannot call a method on a null-valued expression.**

**Comment by JustinGrote** [comment]
Oops! I knew I forgot something, I got psm1 in there but not ps1. Thanks!

**Comment by JustinGrote** [comment]
Should be fixed now, thanks again.
