### ISSUE TITLE
`Get-ModuleFastPlan`: Fails when resolving Pester 4.10.1

### ISSUE THREAD

**Issue by johlju** [JustinGrote/ModuleFast#19]
When calling with the following:

```powershell
@('Pester@4.10.1') | Get-ModuleFastPlan
```

It fails with:

```plaintext
Get-ModuleFastPlan: Exception calling "GetResult" with "0" argument(s): "Response status code does not indicate success: 501 (Not Implemented)."
````

But calling this do work:
```powershell
@('PSPKI@3.7.2') | Get-ModuleFastPlan
``` 

>[!NOTE]
>Using the code in `main` branch.

**Comment by johlju** [comment]
Actually calling `@('Pester') | Get-ModuleFastPlan` returns nothing for me either which is strange. I only have Pester v3.4.0 installed so expected that to return latest version of Pester.

**Comment by johlju** [comment]
If I remove the path entry in $env:PSModulePath that points to Pester v.3.4.0 this issue still exist but now it finds the latest Pester version

```powershell
PS> @('Pester!') | Get-ModuleFastPlan

Name   ModuleVersion
----   -------------
Pester 5.5.0

PS> @('Pester') | Get-ModuleFastPlan

Name   ModuleVersion
----   -------------
Pester 5.5.0

PS> @('Pester@4.10.1') | Get-ModuleFastPlan
Get-ModuleFastPlan: Exception calling "GetResult" with "0" argument(s): "Response status code does not indicate success: 501 (Not Implemented)."
```

**Comment by johlju** [comment]
Possible related issue: https://github.com/JustinGrote/ModuleFast/issues/20

**Comment by JustinGrote** [comment]
Need to make sure you're using preview gallery. Current gallery has prefetch issues for older releases.
![image](https://github.com/JustinGrote/ModuleFast/assets/15258962/0f478a0c-39a1-4c27-93ad-febced691e6e)

On next release preview will get promoted to prod and make these go away.

**Comment by johlju** [comment]
I'm using preview gallery. It's just Get-ModuleFastPlan that has this issue. Using Install-ModuleFast it works for some reason. But will use verbose and debug to see what it reports. Didn't think of that initially.

**Comment by johlju** [comment]
I can't reproduce now, so it must be as you said that I didn't go against the preview gallery, must have been that for some reason I tried in a new session without the default parameter available. Sorry. Closing this. :)
