### ISSUE TITLE
ModuleFast adds trailing zeros to version numbers

### ISSUE THREAD

**Issue by o-l-a-v** [JustinGrote/ModuleFast#3]
## Reproduce
Install [SetBIOS](https://www.powershellgallery.com/packages/SetBIOS/1.0) which in PowerShellGallery has version `1.0`.

## What happens
ModuleFast creates a folder `1.0.0`, instead of `1.0`.

This is a problem because

* ModuleFast installs duplicate on top of what is already installed by PowerShellGet or PackageManagement.
* Sorting on `[System.Version]`, `1.0.0` counts as newer/higher than `1.0`.

## Expected behavior
ModuleFast does not modify version number from PowerShellGallery.

## Screenshot

![image](https://user-images.githubusercontent.com/6450056/213146041-04270098-5a8b-4d0a-96fc-e2f527177098.png)

First folder `1.0` was installed by `PackageManagement\Save-Package`, `1.0.0` was installed using ModuleFast.

**Comment by JustinGrote** [comment]
@o-l-a-v sorry for the delay, I observed this too. It has to do with the very complicated logic we need to do to reconcile both the legacy .NET version syntax and the new semantic versioning syntax.

**Comment by JustinGrote** [comment]
Closed https://github.com/JustinGrote/ModuleFast/commit/212fb1a2ca2b824b5a72eb070a605f59ba0aafd8
