### ISSUE TITLE
`Installl-ModuleFast`: Make a `PassThru` parameter return an object instead of `WhatIf`?

### ISSUE THREAD

**Issue by johlju** [JustinGrote/ModuleFast#34]
Maybe move the output to a `PassThru` parameter instead? That would be more intuitive that something is returned. 🤔

_Originally posted by @johlju in https://github.com/JustinGrote/ModuleFast/issues/27#issuecomment-1868346122_

**Comment by johlju** [comment]
Also see https://github.com/JustinGrote/ModuleFast/issues/27#issuecomment-1868345936.

**Comment by JustinGrote** [comment]
`PassThru` is different, `PassThru` will eventually return the *installed* modules information. That's different than a *plan* of what modules to install.

I haven't decided yet whether those will be native `PSModuleInfo` objects so you can straight import them, or if they will be ModuleInfo objects.

**Comment by johlju** [comment]
Yes, agree `PassThru` should be used for the actually modules that was installed. Didn't think that far ahead 🙂
