### ISSUE TITLE
Command added to my Profile throws errors on load

### ISSUE THREAD

**Issue by ninmonkey** [JustinGrote/ModuleFast#4]
[At first I thought it your PSModulePath covered this](https://github.com/JustinGrote/ModuleFast#note-recommended-psmodulepath-prerequisite), but then the profile code broke. 

## Summary

- The addition to the `$profile` gives the error `The term '$env:PSModulePath' is not a command`
- The **install works**, but `Get-Module -List -All ugit` does not find it.
- `FastInstall -WhatIf ugit` errors, but I expected that. `Resolve-Path: Cannot find path 'C:\Users\cppmo_000\AppData\Local\powershell\Modules' because it does not exist.`

After it writes to my profile, and restart wt, the profile code throws this error

```ps1
$env:PSModulePath: The term '$env:PSModulePath' is not recognized as a name of a cmdlet, function, script file, or executable program.
```
```ps1
# The module is installed correctly
> Test-Path C:\Users\cppmo_000\AppData\Local\powershell\Modules\ugit
True
impo C:\Users\cppmo_000\AppData\Local\powershell\Modules\ugit\0.4.0\ugit.psd1
 # loads..
```
## Code added to the profile:

```ps1
if ('$Destination' -notin ($env:PSModulePath.split([IO.Path]::PathSeparator))) { `$env:PSModulePath = '$Destination' + $([IO.Path]::PathSeparator + $env:PSModulePath) } <#Added by ModuleFast. DO NOT EDIT THIS LINE. If you do not want this, add -NoProfileUpdate to Install-ModuleFast or add the default destination to your powershell.config.json or to your PSModulePath another way.#>
```
which runs as

![image](https://github.com/JustinGrote/ModuleFast/assets/3892031/38813272-dddf-42b1-a069-e84fd5fa65c3)

Before running, I have:

| Path | Exists | 
| - | - | 
| `C:\Users\cppmo_000\SkyDrive\Documents\PowerShell\Modules` | True | 
| `C:\Users\cppmo_000\AppData\Local\powershell` | True |
| `C:\Users\cppmo_000\AppData\Local\powershell\Modules` | False |

![image](https://github.com/JustinGrote/ModuleFast/assets/3892031/f94f76f0-c2df-4ad9-bffb-aca9107cca07)

![image](https://github.com/JustinGrote/ModuleFast/assets/3892031/c19baba3-a14f-4ece-a628-af264aec1c53)

## Location  of Exception

```ps1
Cannot find path 'C:\Users\cppmo_000\AppData\Local\powershell\Modules' because it does not exist.
C:\Users\cppmo_000\SkyDrive\Documents\PowerShell\Modules\ModuleFast\0.0.4\ModuleFast.psm1:60 char:25
                           +     [string]$Destination = Resolve-Path $Destination
```

**Comment by ninmonkey** [comment]
In case it helps, here's the full contents

```ps1
$Env:PSModulePath = @(
    $Env:PSModulePath
    $toAdd = gi 'E:\PSModulePath.2023.root\Main' # assume this exists
) | Join-String -sep ([IO.Path]::PathSeparator)

# $Profile.CurrentUserAllHosts: shared (all3): VSCode, VSCode Debug Term, and windows term (external)

if($global:__nin_enableTraceVerbosity) { "⊢🐸 ↪ enter Pid: '$pid' `"$PSCommandPath`". source: VsCode, term: regular, prof: AllUsersCurrentHost" | Write-Warning; }[Collections.Generic.List[Object]]$global:__ninPathInvokeTrace ??= @(); $global:__ninPathInvokeTrace.Add($PSCommandPath); <# 2023.02 #>

. (Get-Item -ea 'continue' (Join-Path $Env:Nin_Dotfiles 'pwsh/profile.ps1'))

if($global:__nin_enableTraceVerbosity) { "⊢🐸 ↩ exit  Pid: '$pid' `"$PSCommandPath`". source: VsCode, term: regular, prof: AllUsersCurrentHost" | Write-Warning; }[Collections.Generic.List[Object]]$global:__ninPathInvokeTrace ??= @(); $global:__ninPathInvokeTrace.Add($PSCommandPath); <# 2023.02 #>

 if ('$Destination' -notin ($env:PSModulePath.split([IO.Path]::PathSeparator))) { `$env:PSModulePath = '$Destination' + $([IO.Path]::PathSeparator + $env:PSModulePath) } <#Added by ModuleFast. DO NOT EDIT THIS LINE. If you do not want this, add -NoProfileUpdate to Install-ModuleFast or add the default destination to your powershell.config.json or to your PSModulePath another way.#> 
 ````

**Comment by JustinGrote** [comment]
@ninmonkey I'll have a release soon that should fix this, you can try the instructions in README to test the latest MAIN version and see if it still happens.

**Comment by JustinGrote** [comment]
@ninmonkey should be fixed, though it may cause a duplicate profile entry now as I think the format changed slightly. If you have your destination in your PSModulePath, already, it should skip the profile add step.
