### ISSUE TITLE
Make ThrottleLimit more automatic?

### ISSUE THREAD

**Issue by johlju** [JustinGrote/ModuleFast#46]
Just a thought. It says in the help:

>If your system uses HyperThreading and presents more logical cores than physical cores available, **you may want to set this to half your number of logical cores for best performance**.

Would it be possible to detect if hyper threading is enabled and limit the cores used automatically?

**Comment by JustinGrote** [comment]
@johlju detecting hyperthreading is complicated and OS-specific, but even if hyperthreading is present, it shouldn't impact performance *that* much, it just means two decompression threads that are on the same processor will each take half as long (with some minor additional context switching overhead) but ultimately probably complete within 80-90% of the performance of the normal threads, it's a minor performance boost in most scenarios, not a huge one.
