### ISSUE TITLE
Can not use `-Release` on bootstrap script with `0.1.0`

### ISSUE THREAD

**Issue by johlju** [JustinGrote/ModuleFast#54]
The documentation says:

https://github.com/JustinGrote/ModuleFast/blob/096d87104655892a601cd879af8929ad79bd028c/README.MD?plain=1#L41

But the version need to be prefixed with 'v'.

```powershell
PS> & ([scriptblock]::Create((iwr 'bit.ly/modulefast'))) -Release '0.1.0'
: Failed to fetch ModuleFast from https://github.com/JustinGrote/ModuleFast/releases/download/0.1.0/ModuleFast.psm1: Exception calling "GetResult" with "0" argument(s): "Response status code does not indicate success: 404 (Not Found)."
PS> & ([scriptblock]::Create((iwr 'bit.ly/modulefast'))) -Release 'v0.1.0'
PS>
```

**Comment by johlju** [comment]
Either the docs need to be changed or bootstrap script should add the missing 'v' if it is not passed. 🤔

**Comment by JustinGrote** [comment]
To avoid breaking anyone who is already got it working, I will update the docs.
