### ISSUE TITLE
Release version doesn't match PSGallery version

### ISSUE THREAD

**Issue by ThomasNieto** [JustinGrote/ModuleFast#55]
The latest release on this repository is 0.1.0 while the latest version on PSGallery is 0.1.1. I believe you may have a bug in your module version bumping code.

**Comment by JustinGrote** [comment]
@ThomasNieto that was sort of on purpose, I didn't want to update the release notes but had to fix a problem in the gallery version where it included a nested zip.

This has been re-united with 0.1.2. Thanks for the note however!
