### ISSUE TITLE
AnyPackage Provider

### ISSUE THREAD

**Issue by ThomasNieto** [JustinGrote/ModuleFast#75]
A ModuleFast AnyPackage provider has been published. Give it a shot and let me know if you run into any issues: https://www.powershellgallery.com/packages/AnyPackage.ModuleFast

**Comment by JustinGrote** [comment]
Awesome! When I get done with the next release and Github Action I'll try it out and make sure it is compatible. You're the best!

**Comment by JustinGrote** [comment]
@ThomasNieto Looks pretty good! Some thoughts:
1. You could use Install-ModuleFast -Plan to provide a package get/find operator
2. It currently reports `Package Not Found` if a package is already installed. On my todo is to fix both -Plan and -PassThru to include modules that were part of the plan but already installed, once I fix that it will probably report more "correctly"

**Comment by ThomasNieto** [comment]
@JustinGrote

1. I like the idea of adding `Find` operator to support the `Plan` parameter.
2. The problem is that the provider interface only handles one package at a time to property cycle through each provider if a package isn't found. The provider interface does support handling `ShouldProcess` calls so that if the user says `Yes to All` it would work for all packages and providers. That was a common problem in OneGet where it would keep prompting. I have also thought  of adding a `PromptDependencies` for providers to indicates this package would also include X dependencies. Then the user would be able to say `Yes to All` for all package dependencies for as many packages or providers called in a single invoke. I do something similar with `PromptUntrustedSource` where if an untrusted source is called multiple times if `Yes to All` or `No to All` is honored. If you have any ideas I'd be welcome to hear them.
3. That would work

**Comment by ThomasNieto** [comment]
Find-Package support was added in the latest release (v0.1.2)

**Comment by JustinGrote** [comment]
I'm going to close this as it seems to work great for me, thanks @ThomasNieto!
