### ISSUE TITLE
Help Example 5 suggests pipeline binding that does not work

### ISSUE THREAD

**Issue by Jaykul** [JustinGrote/ModuleFast#86]
This does not work, since there are no pipeline-bound parameters:
https://github.com/JustinGrote/ModuleFast/blob/1dfe7d67caa45b1fefd3db5ec84d25ad895b94ed/ModuleFast.psm1#L151

**Comment by Jaykul** [comment]
I take it back. This works, the problem is that the ModuleVersion doesn't support nuget ranges. 

I really don't understand the way you've done versioning.

**Comment by JustinGrote** [comment]
@Jaykul that syntax only supports legacy ModuleSpecification format, and that format doesn't support nuget ranges, it's there for compatibility. Same goes for PSGetv3.

I recommend the "string" syntax for nuget ranges.
