### ISSUE TITLE
Prerelease Versions with string syntax incorrectly cast to [System.Version]

### ISSUE THREAD

**Issue by Jaykul** [JustinGrote/ModuleFast#88]
Right now, if you run:

```PowerShell
Find-PSResource ModuleBuilder -Prerelease
```
The current prerelease is:
```
Name          Version Prerelease           Repository Description
----          ------- ----------           ---------- -----------
ModuleBuilder 3.2.0   scriptgenerators0009 PSGallery  A module for authoring and building PowerShell modules
```

But if I try to use the pre-release with Install-ModuleFast, I can't find a way to do it without accepting pre-release of everything

I would expect any of these to work:
```PowerShell
Install-modulefast "ModuleBuilder:[3.2.0-scriptgenerators0009, 4.0)"
install-modulefast "ModuleBuilder>=3.2.0-alpha"
install-modulefast "ModuleBuilder>=3.2-alpha"
```

Currently, the only way I can find to install it is to explicitly use the `-Prerelease` switch:
```
install-modulefast "ModuleBuilder>3.1" -Prerelease
```

**Comment by JustinGrote** [comment]
Thanks for the submission, I see my test succeeds but can confirm yours doesn't, time to see what's different between ModuleBuilder and PrereleaseTest

**Comment by JustinGrote** [comment]
Seems to be an issue when the module is already installed. If not installed it doesn't happen, something in that compare logic isn't working right.
![image](https://github.com/user-attachments/assets/da429c8b-21d0-4854-be6d-a3ac82bf16a2)

**Comment by JustinGrote** [comment]
@Jaykul found it, simple oopsie when doing a local version compare against a prerelease install. Should be good now.
