### ISSUE TITLE
new feature: Get-Module -ListAvailable ?

### ISSUE THREAD

**Issue by rismoney** [JustinGrote/ModuleFast#95]
A typical scenario I am seeing is I still need to rely on Get-module -ListAvailable to make a determination if I need to install a module declaratively.  This can be quite an expensive operation too.  Have you thought about adding a faster method of this?  I am not totally sure why, but on a cold powershell launch this could a seemingly long time depending on module size/count to enumerate.
I feel like maybe there is some poor evaluation of psmodulepath happening here via iteration or something else underlying that is super ineffecient.

I welcome your thoughts

**Comment by JustinGrote** [comment]
Also, `Install-ModuleFast -WhatIf` produces a report of what will be updated based on your module specifications. If it doesn't show up in the list, the installed modules meet your criteria (-Verbose and -Debug to learn more), so you don't have to do this comparison manually.

Going to close as "won't fix", but I will provide a function to give you an idea of how it could be "faster" as long as you don't need to know what commands are in a module.

**Comment by JustinGrote** [comment]
@rismoney here's a script to kinda sorta do what you want.
https://gist.github.com/JustinGrote/4cebf646cabd39a435e796754dfa0de1
