### ISSUE TITLE
Fails to get preview version using `!`

### ISSUE THREAD

**Issue by johlju** [JustinGrote/ModuleFast#97]
This has stopped working. I was scratching my head why changes in a module did not got to my dev machine until I realised I got the full release and not the latest preview. This has worked before and I'm not sure when it stopped working. I'm using the latest ModuleFast from `bit.ly/modulefast`.

```powershell
$installModuleFastParameters = @{
    Destination          = 'C:\source\SqlServerDsc\output\RequiredModules'
    DestinationOnly      = $true
    NoPSModulePathUpdate = $true
    NoProfileUpdate      = $true
    Update               = $true
    Confirm              = $false
}

Install-ModuleFast -Specification 'DscResource.DocGenerator!' -Plan @installModuleFastParameters
```

Result (full release instead of preview):

```plaintext
Name                     ModuleVersion Location
----                     ------------- --------
DscResource.DocGenerator 0.12.5        https://pwsh.gallery/flatcontainer/dscresource.docgenerator/0.12.5/dscresource.docgenerator.0.12.5.nupkg
```

It should have gotten 0.13.0-preview0001: https://www.powershellgallery.com/packages/DscResource.DocGenerator/0.13.0-preview0001

**Comment by JustinGrote** [comment]
It's not on the pwsh.gallery but it's on old.pwsh.gallery so something in the updater must be broken.

`imf 'DscResource.DocGenerator!' -Update -Whatif -Source 'https://old.pwsh.gallery/index.json' -verbose -debug`

**Comment by JustinGrote** [comment]
Looks like the updater is working but only for non-prerelease packages, I'll look into it
![image](https://github.com/user-attachments/assets/9effb377-3b19-489f-a93d-a3301a0a7b34)

**Comment by JustinGrote** [comment]
It showed up in the query, maybe something in sleet didnt want to push it
![image](https://github.com/user-attachments/assets/4cd7f9af-3728-4466-a525-3eeb3d57e744)

**Comment by JustinGrote** [comment]
Found the problem. In my query builder I was using `$true` for `includePrerelease`, which resolves to capital-T True instead of true, which doesn't work :/

Yay for case sensitive bugs. Anyways, I'll clear the checkpoint which should pick up all packages for the last 3 days and get your prerelease, as well as others going forwards.

**Comment by JustinGrote** [comment]
Fixed:
![image](https://github.com/user-attachments/assets/d495f85c-6fac-4265-8bbf-52f84f105609)

**Comment by johlju** [comment]
Thank you! Much appreciated that you could resolve it so quickly. PSResourceGet was very slow as a workaround 🙂
